const descriptionBank =
    [
        "The future is a blank page.",
        "Tomorrow's adventures await.",
        "The journey is just beginning.",
        "The best is yet to come.",
        "New chapters are on the horizon.",
        "The story continues.",
        "The ending is not yet written.",
        "Endings are just new beginnings.",
        "A new dawn is rising.",
        "Your story is still unfolding.",
        "The plot thickens.",
        "Life's greatest moments are ahead.",
        "The next page is blank.",
        "The adventure has just started.",
        "The horizon is full of promise.",
        "The journey awaits.",
        "A new saga begins.",
        "The future holds endless possibilities.",
        "Tomorrow's pages are empty.",
        "The story is far from over.",
        "The tale is still unfolding.",
        "The journey has just begun.",
        "The next chapter awaits.",
        "The adventure continues.",
        "The story is still being written.",
        "A new path is opening.",
        "The best parts are yet to come.",
        "The future is wide open.",
        "The next adventure awaits.",
        "A new journey begins.",
        "The future is a mystery.",
        "The story is still in progress.",
        "The next steps are yours to take.",
        "A new chapter is about to begin.",
        "The future is an open book.",
        "The journey is ongoing.",
        "The next adventure is around the corner.",
        "The story is still evolving.",
        "The path ahead is uncharted.",
        "The next page is waiting to be filled.",
        "The future is yet to unfold.",
        "The story is yet to be completed.",
        "The best chapters are yet to be written.",
        "The next journey is on the horizon.",
        "The story continues to grow.",
        "The road ahead is full of promise.",
        "The future is a blank canvas.",
        "The adventure is just beginning.",
        "The story is still in the making.",
        "The next chapter is unwritten.",
        "The future is full of potential.",
        "The story is far from finished.",
        "The next steps are unwritten.",
        "The adventure is yet to unfold.",
        "The story is yet to be fully told.",
        "The journey is still unfolding.",
        "The future is yet to be defined.",
        "The story has many pages left.",
        "The best part of the journey is ahead.",
        "The story is still an open book.",
        "The journey is far from over.",
        "The future is still a mystery.",
        "The story is still being crafted.",
        "The best is yet to be written.",
        "The next journey is just beginning.",
        "The story is still in its early stages.",
        "The path ahead is still being discovered.",
        "The future is still being written.",
        "The journey is still being mapped out.",
        "The best part is still to come.",
        "The story has yet to unfold.",
        "The next adventure is just starting.",
        "The future is still an unwritten story.",
        "The journey is still in progress.",
        "The best chapters are yet to unfold.",
        "The story is still being lived.",
        "The path ahead is still untraveled.",
        "The story is still a work in progress.",
        "The next steps are still being planned.",
        "The adventure is still on the horizon.",
        "The future is still a blank slate.",
        "The journey is still to be experienced.",
        "The story is still unfolding every day.",
        "The best is still ahead.",
        "The future is still untold.",
        "The story is still being imagined.",
        "The path ahead is still unwritten.",
        "The story is still a journey in the making.",
        "The best is still waiting to be written.",
        "The future is still an untold adventure.",
        "The journey is still awaiting discovery.",
        "The story is still in its infancy.",
        "The path ahead is still to be explored.",
        "The future is still an untold tale.",
        "The journey is still an ongoing story.",
        "The best part is still unwritten.",
        "Shadows conceal what is yet to come.",
        "The unknown lies ahead.",
        "In the mists of time, secrets wait.",
        "Tomorrow's mysteries await discovery.",
        "Enigma shrouds the future.",
        "Destiny's veils are yet to lift.",
        "A cryptic journey continues.",
        "Arcane paths remain hidden.",
        "Life's labyrinth unfolds.",
        "Mystic futures are unwritten.",
        "Fate's riddle remains unsolved.",
        "Unknown paths call out.",
        "Fog shrouds tomorrow's way.",
        "Future whispers its secrets.",
        "Hidden stories surface slowly.",
        "Mystery deepens with each step.",
        "Veils of the future remain drawn.",
        "An enigmatic journey unfolds.",
        "Secret chapters remain unread.",
        "Shadows of destiny loom ahead.",
        "A cryptic future awaits.",
        "Concealed paths remain unwalked.",
        "Mystic tales are far from over.",
        "An obscure journey continues.",
        "Hidden paths remain undiscovered.",
        "An arcane story unfolds.",
        "Secrets of fate remain veiled.",
        "A mysterious journey lies ahead.",
        "Destiny's enigma awaits.",
        "A concealed future remains unknown.",
        "Mystic paths remain unwalked.",
        "A cryptic tale continues to unfold.",
        "Future remains a mystery.",
        "Unknown destiny awaits discovery.",
        "Secrets of tomorrow remain shrouded.",
        "Enigmatic paths lie ahead.",
        "Arcane futures remain unwritten.",
        "A cryptic journey awaits.",
        "Veiled future beckons.",
        "Hidden stories remain untold.",
        "An enigmatic future remains a mystery.",
        "Unknown tales remain untold.",
        "Concealed journeys lie ahead.",
        "Arcane paths await discovery.",
        "A cryptic future remains unknown.",
        "Mystic journeys continue.",
        "Hidden chapters remain unwritten.",
        "Fate's secrets remain concealed.",
        "An enigmatic tale unfolds.",
        "Unknown paths remain unwalked.",
        "Concealed futures are a mystery.",
        "A cryptic journey remains unfinished.",
        "Hidden destinies await.",
        "Arcane stories remain untold.",
        "Secrets of tomorrow remain veiled.",
        "An enigmatic journey beckons.",
        "Unknown futures await revelation.",
        "Concealed tales are far from over.",
        "Cryptic paths lie ahead.",
        "Hidden futures remain an enigma.",
        "Fate's secrets remain untold.",
        "Arcane journeys continue.",
        "Concealed stories surface slowly.",
        "Enigmatic paths call out.",
        "Unknown destinies lie ahead.",
        "A cryptic future awaits discovery.",
        "Hidden tales continue to unfold.",
        "Tomorrow's secrets remain shrouded.",
        "Arcane paths remain concealed.",
        "An enigmatic journey lies ahead.",
        "Unknown futures remain unwritten.",
        "Cryptic stories are still in progress.",
        "Hidden paths await discovery.",
        "Fate's secrets remain veiled.",
        "An arcane tale unfolds.",
        "Concealed futures beckon.",
        "Enigmatic paths remain unwalked.",
        "Unknown journeys remain unfinished.",
        "A cryptic future remains a mystery.",
        "Hidden stories remain untold.",
        "Tomorrow's secrets lie ahead.",
        "Arcane journeys are far from over.",
        "Concealed paths await revelation.",
        "An enigmatic tale beckons.",
        "Unknown destinies remain unknown.",
        "Cryptic futures remain concealed.",
        "Hidden journeys continue to unfold.",
        "Fate's secrets remain shrouded.",
        "Arcane paths call out.",
        "An enigmatic story lies ahead.",
        "Unknown futures remain a mystery.",
        "A cryptic tale remains untold."
    ]

export default function getRandomDescription() {
    function randomNum() { return Math.floor(Math.random() * 200); }

    return `${descriptionBank[randomNum()]}`
}

